name: Release

on:
  push:
    branches:
      - dev

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install PNPM
        run: npm i pnpm -g

      - name: Install Dependencies
        run: pnpm i -r

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Notification
        if: steps.changesets.outputs.published == 'true'
        run: echo "🎉 Release created! "
